select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE UPPER(discount_applied) = 'YES' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product Rating"
from customer
group by item_purchased
order by  avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard,Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between

select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applie
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN UPPER(discount_applied) = 'YES' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

--Q8 What are the top 3 most purchased products within each category?

--09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

--Q10. What is the revenue contribution of each age group?